server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_center?useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: root
